#!/bin/bash
file=$1
while IFS= read -r line
do
 
#printf '%s\n' "$line" 
check=`echo $line | sed -e 's/^[[:space:]]*//'`
echo $line
read -r mystring </dev/tty
while [ "$check" != "$mystring" ];
do
comm -23 <(echo $check | tr ' ' '\n' | sort) <(echo $mystring | tr ' ' '\n' | sort)

printf '%s\n' "Try again"

read mystring </dev/tty
done

done <"$file"
